services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      target: frontend
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:80" # 프론트엔드가 Nginx를 통해 서빙되면 80번 포트를 3000번으로 매핑

  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: backend
    # init 프로세스 실행해서 SIGTERM 시그널 대응
    init: true
    environment:
      - TZ=Asia/Seoul
    ports:
      - "4000:4000" # 백엔드가 4000번 포트를 사용
